#include <lpc214x.h>

/* MACRO DEFINITION */
#define RS   (1<<10)
#define RW   (1<<12)
#define EN   (1<<13)
#define LCD_DATA  (0xFF<<16)
#define CUT_OFF_FULL 1000
#define CUT_OFF_MID 600
#define CUT_OFF_END 200
#define PIN_1 (1<<1)
#define LED_G 0xC0
#define LED_Y 0xA0
#define LED_R 0x90
#define LED_CLEAR 0x70
#define BUZZER (1<<15)

/* FUNCTION DECLARATION */
void LCD_display(char *);
void LCD_data(unsigned char a);
void LCD_command (unsigned char a);
/* DELAY FUNTION */
void delay(int count)
{
int i,j;
for(i =0;i < count;i++)
for(j = 0;j < 5000;j++);
}
/* LCD INITIALIZATION */
void LCD_init(void)
{
IODIR0 |= EN|RS|RW|LCD_DATA;
LCD_command(0X38); 		//intializes the 16x2 ,5x7 LCD matrix  8-bit mode
LCD_command(0X0F); 		//  display on cursor blinking
LCD_command(0X01); 		//clear screen ,cursor home
LCD_command(0X80);		//Start with first line
}
/* DISPLAY FUNCTION FOR STRINGS in lcd */
void LCD_display(char *str)
{
while(*str)
{
{
LCD_data(*str);
}
str++;
delay(50);
}
}

/* LCD DATA TRANSFER FUNCTION */
void LCD_data(unsigned char a)
{
IOPIN0 = a << 16;
IOCLR0 = RW;//SETTING PORT ZERO PIN 12 READ WRITE MODE
IOSET0 = RS;  //RS=1 for data//ENABLING RESET PIN PORT 0 PIN 10
IOSET0 |= EN;//ENABLING THE PORT 0 PIN 13 BY SEETING 1 THIS PIN WE ARE ENABLING THE CONTROLLER I/O FUNCTIONS
delay(100);
IOCLR0 = EN;//CLAERING THE ENABLED VALUE
delay(100);
}

/* LCD COMMAND FOR PASS COMMAND TO LCD */
void LCD_command (unsigned char a)
{
IOPIN0 = a<<16;
IOCLR0 = RS;	//RS should be 0 for command
IOCLR0 |= RW;
IOSET0 = EN;
delay(100);
IOCLR0 = EN;
delay(100);
}

/* DISPLAY FUNCTION FOR INTEGER TO ASCII VALUE CONVERSION */
void display(int a) // display the integer on lcd by converting integer into ascii
{
 //LCD_command(0x01);
 //LCD_command(0xC0);
if(a != 0)
{
display(a/10);
LCD_data(a%10 + 48);
}
}

/* MAIN FUNCTIONN */
int main()
{
int res;
IO0DIR |= 0xF0;//SETTING DIRECTION
LCD_init();//CALLING LCD_INITIALIZATION TO ACTIVATE LCD
LCD_display("FUEL LEVEL");//DISPLAYING THE STRING WITH HELP OF LCD_DISPLAY FUNCTION
delay(500);//GIVING SOME SECONDS DEALY IN FUNCTION
PINSEL1= ((1<<18)|(0<<19));   //ENABLING PIN AS ADC(P0.25 as AD0.4) PRIMARY FUNCTION
AD0CR = 0x00200310;  //LDR AS PER SCHEMATIC WE ARE ENABLING LDR SENSOR
while(1)//giving while loop for continious checking till the ignition is off
{
if(IO0PIN & PIN_1)//SETTING PORT O PIN 1 AS INPUT PIN.INITIALLY ASSIGNING THIS PIN IS ON STATE.(IGNITION ON)(IF THE PIN IS CONNECTED WITH GROUND IT WILL OFF STATE THAT'S WE DONE BY JUMBER WIRE)
{
LCD_command(0X80);//IF THE ABOVE CONDITION IS TRUE WE ARE SETTING LCD CURSER AS FIRST ROW AND FIRST COLUMN
AD0CR = AD0CR | (1<<24); // WE ARE INITIALIZING ADC 0 REGISTER AS CONVERSION MODE(SEARCH THE FRMAE FORMATE OF A/D CONVERTER FRAME FORMET OF LPC2148 IN THE BROWSER AND SEE WHAT IS 24 BIT)
while ( !(AD0GDR & 0x80000000) ); //WE ASKING THE REGISTER WAIT TILL DONE
res = AD0GDR;//WE ARE STORING THE REGISTER VALUE TO RES
res = (res>>6);//THEN WE ARE MOVING DATA FROM 0 TO 6 BIT BECAUSE WE CAN'T ACCES TO TILL 6 BIT
res = (res & 0x000003FF);
LCD_command(0xC0);//SETTING LCD CURSOR IN 2 ROW 1 COLUMN
display(res);	//DISPLAYING THE DATA WHAT WE COLLECTED FROM ADC REGISTER(EX:TEMPRATURE)

/*BASED UPON THAT ABOVE VALUE WE ARE MAKING DECISION MAKING STATEMENT */
if (res > CUT_OFF_FULL)//IF IT IS HIGH
{
IO0SET |= LED_G;//ENABLING LED PORT O PIN 12(AS PER DEVELOPMENT BOARD PIN CONFIGURATION)
delay(1000);
}
else if ((res > CUT_OFF_MID) && (res <CUT_OFF_FULL))//IF IT IN B/W THIS RANGE
{
IO0CLR |= LED_CLEAR;//FIRST WE ARE CLEARING THE LED WHAT WE ASSIGNED BEFORE
IO0SET |= LED_Y;//THEN WE ARE ENABLING NEXT LED IN THE BOARD AS PER PIN
delay(1000);
}

else if ((res < CUT_OFF_MID) && (res >CUT_OFF_END))//IF IT IN B/W THIS RANGE
{
IO0CLR |= LED_CLEAR;//FIRST WE ARE CLEARING THE LED WHAT WE ASSIGNED BEFORE
IO0SET |= LED_R;//THEN WE ARE ENABLING NEXT LED IN THE BOARD AS PER PIN
delay(1000);
}

else if (res < CUT_OFF_END)//IF IT IS LOW
{
IO0CLR |= LED_CLEAR;//FIRST WE ARE CLEARING THE LED WHAT WE ASSIGNED BEFORE
IO0DIR |= BUZZER;//SETTING DIRECTION OF THE CONTOLLER WE ASKING TO GO TO BUZZER PIN
IO0SET |= BUZZER;//THEN WE ARE ENABLING THE BUZZER (TURN ON)
delay(1000);
IO0CLR |= BUZZER;//TURNING OFF THE BUZZER
IO0CLR |= LED_CLEAR;//AGIN CLEARING THE LED(I DONT KNOW IT IS REUIRED OR NOT)
delay(1000);
}
delay(1000);
}
else //IF THE IGINITION PIN IS WENT OFF STATE(WITH CONNECTED WITH GROUND IN OUR BOARD)
{
LCD_display("Ignition off");//IT WILL PRINT THIS IN LCD
delay(1000);
LCD_command(0x01);//WE ARE CLEARING THE SCREEN AND SETTING CURSOR TO START
}
}
}
